server:
  port: 8087
  servlet:
    context-path: /api/v2/
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8880/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update